# Generated by Django 2.0.1 on 2023-10-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='food_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('FOOD', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.food')),
            ],
        ),
        migrations.CreateModel(
            name='food_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=100)),
                ('buiding_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('FOOD_ITEMS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.food_items')),
            ],
        ),
        migrations.CreateModel(
            name='order_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('house_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ORDER_MASTER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.order_master'),
        ),
        migrations.AddField(
            model_name='food_items',
            name='FOOD_PROVIDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.food_provider'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='FOOD_ITEMS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.food_items'),
        ),
        migrations.AddField(
            model_name='cart',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.user'),
        ),
        migrations.AddField(
            model_name='bank',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.login'),
        ),
    ]
