# Generated by Django 2.0.1 on 2023-10-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homely_meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_provider',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homely_meals.login'),
        ),
    ]
