# Generated by Django 2.0.1 on 2023-10-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely_meals', '0003_auto_20231007_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_provider',
            name='email',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='order_master',
            name='status',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
